version: '3'
services:
    world_server:
        build:
            context: ./server
            dockerfile: Dockerfile-dev
        image: server
        volumes:
            - ./server:/app
        environment:
            - VENUELESS_DB_NAME=venueless
            - VENUELESS_DB_USER=venueless
            - VENUELESS_DB_PASS=venueless
            - VENUELESS_DB_HOST=db
            - VENUELESS_DATA_DIR=/data
        entrypoint: ["bash", "/app/world_server/docker-dev-entrypoint.sh"]
        depends_on:
            - db
    websocket_worker:
        image: server
        ports:
            - "8375:8375"
        volumes:
            - ./server:/app
        entrypoint: ["bash", "/app/websocket_worker/docker-dev-entrypoint.sh"]
        depends_on:
            - db
            - world_server
    db:
        image: "postgres:13"
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=venueless
            - POSTGRES_PASSWORD=venueless
volumes:
    postgres_data:
# networks:
#   default:
#     ipam:
#       config:
#         - subnet: 172.177.0.0/16
