FROM python:3.9

COPY requirements.txt /requirements.txt
RUN pip3 install -U pip wheel setuptools && pip3 install -Ur requirements.txt
ENV VENUELESS_COMMIT_SHA=devcontainer
ENV PYTHONUNBUFFERED=1
WORKDIR /app
EXPOSE 8375
